
## Compute empirical power on a grid of significance level values.
##
GetEmpiricalPower <- function(x, alphaGrid = seq(0.001, 1, by = 0.001)) {
  EmpiricalPower <- function(x, alphaGrid) {
    x <- x[!is.na(x)]
    ntests <- length(x)
    nalpha <- length(alphaGrid)
    out <- rep(NA, nalpha)
    for (i in seq(nalpha)) {
      out[i] <- sum(x <= alphaGrid[i])/ntests
    }
    out
  }
  apply(x, 2, EmpiricalPower, alphaGrid)
}


## Load the outputs from the
## simulation studies generated by
## the scripts:
##
## run_simulations_H1c_H1d.R
## run_simulations_H1c_H0d.R
## run_simulations_H0c_H0d.R
## run_simulations_H0c_H1d.R

load("sim_study_H1c_H1d_weak.RData")
out11w <- out
load("sim_study_H1c_H1d_moderate.RData")
out11m <- out
load("sim_study_H1c_H1d_strong.RData")
out11s <- out

load("sim_study_H1c_H0d_weak.RData")
out10w <- out
load("sim_study_H1c_H0d_moderate.RData")
out10m <- out
load("sim_study_H1c_H0d_strong.RData")
out10s <- out

load("sim_study_H0c_H0d.RData")
out00 <- out

load("sim_study_H0c_H1d.RData")
out01 <- out




## Compute the empirical for the
## simulations under H_1^c, H_1^d
##
epdat11 <- data.frame(out11w[, c("confoundingPval")],
                      out11m[, c("confoundingPval")],
                      out11s[, c("confoundingPval")])
names(epdat11) <- c("weak", "moderate", "strong")
alphaGrid <- seq(0.001, 0.999, by = 0.001)
ep11 <- GetEmpiricalPower(x = epdat11, alphaGrid = alphaGrid)


## Compute the empirical for the
## simulations under H_1^c, H_0^d
##
epdat10 <- data.frame(out10w[, c("confoundingPval")],
                      out10m[, c("confoundingPval")], 
                      out10s[, c("confoundingPval")])
names(epdat10) <- c("weak", "moderate", "strong")
alphaGrid <- seq(0.001, 0.999, by = 0.001)
ep10 <- GetEmpiricalPower(x = epdat10, alphaGrid = alphaGrid)


## Plot Figure 5

mylwd <- 1

mycols <- c("darkblue", "darkred", "darkgreen")
nmin <- 0

cm <- 1.5
cl <- 1

par(mfrow = c(2, 2), mar = c(4, 3, 2, 0.5), mgp = c(2, 0.75, 0))
plot(alphaGrid, alphaGrid, type = "n", 
     xlab = "significance level", 
     ylab = "empirical power",
     main = expression(paste(italic(H[1]^c), "  ,  " , italic(H[1]^d))))
abline(a = 0, b = 1, col = "grey")
lines(alphaGrid, ep11[, "weak"], type = "l", col = mycols[1], lwd = mylwd)
lines(alphaGrid, ep11[, "moderate"], type = "l", col = mycols[2], lwd = mylwd)
lines(alphaGrid, ep11[, "strong"], type = "l", col = mycols[3], lwd = mylwd)
legend("bottomright", text.col = mycols, bty = "n", cex = cl, 
       legend = c(expression(paste(theta %in% "[0.5, 1.0]")),
                  expression(paste(theta %in% "[1.0, 1.5]")),
                  expression(paste(theta %in% "[1.5, 2.0]"))))
mtext(side = 3, text = "(a)", at = 0)
####
plot(alphaGrid, alphaGrid, type = "n", 
     xlab = "significance level", 
     ylab = "empirical power",
     main = expression(paste(italic(H[1]^c), "  ,  " , italic(H[0]^d))))
abline(a = 0, b = 1, col = "grey")
lines(alphaGrid, ep10[, "weak"], type = "l", col = mycols[1], lwd = mylwd)
lines(alphaGrid, ep10[, "moderate"], type = "l", col = mycols[2], lwd = mylwd)
lines(alphaGrid, ep10[, "strong"], type = "l", col = mycols[3], lwd = mylwd)
legend("bottomright", text.col = mycols, bty = "n", cex = cl, 
       legend = c(expression(paste(theta %in% "[0.5, 1.0]")),
                  expression(paste(theta %in% "[1.0, 1.5]")),
                  expression(paste(theta %in% "[1.5, 2.0]"))))
mtext(side = 3, text = "(b)", at = 0)
####
hist(out01[, "confoundingPval"], probability = TRUE, xlab = "p-values", 
     main = expression(paste(italic(H[0]^c), "  ,  " , italic(H[1]^d))), 
     nclass = 10)
mtext(side = 3, text = "(c)", at = 0)
####
hist(out00[, "confoundingPval"], probability = TRUE, xlab = "p-values",
     main = expression(paste(italic(H[0]^c), "  ,  " , italic(H[0]^d))), 
     nclass = 10)
mtext(side = 3, text = "(d)", at = 0)
par(mfrow = c(1, 1))



## Plot Figure 6

out11 <- rbind(out11w, out11m, out11s)
out10 <- rbind(out10w, out10m, out10s)

myylim <- c(0, 1)

par(mfrow = c(2, 2), mar = c(2.5, 3, 2, 0.5), mgp = c(2, 0.75, 0))
boxplot(out11[, 1:2], ylim = myylim, col = c("cyan", "darkorange"),
        main = expression(paste(italic(H[1]^c), "  ,  " , italic(H[1]^d))))
abline(h = 0.5, col = "red")
mtext(side = 3, text = "(a)", at = 0.5)
boxplot(out10[, 1:2], ylim = myylim, col = c("cyan", "darkorange"),
        main = expression(paste(italic(H[1]^c), "  ,  " , italic(H[0]^d))))
abline(h = 0.5, col = "red")
mtext(side = 3, text = "(b)", at = 0.5)
boxplot(out01[, 1:2], ylim = myylim, col = c("cyan", "darkorange"),
        main = expression(paste(italic(H[0]^c), "  ,  " , italic(H[1]^d))))
abline(h = 0.5, col = "red")
mtext(side = 3, text = "(c)", at = 0.5)
boxplot(out00[, 1:2], ylim = myylim, col = c("cyan", "darkorange"),
        main = expression(paste(italic(H[0]^c), "  ,  " , italic(H[0]^d))))
abline(h = 0.5, col = "red")
mtext(side = 3, text = "(d)", at = 0.5)

